import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#454651",
        "surface-variant": "#e5e2de",
        "surface-container-high": "#ebe8e4",
        "surface-bright": "#fcf9f5",
        "background": "#fcf9f5",
        "outline": "#757683",
        "outline-variant": "#c5c5d3",
        "surface": "#fcf9f5",
        "surface-dim": "#dcdad6",
        "inverse-surface": "#31302e",
        "surface-container-low": "#f6f3ef",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#f0edea",
        "surface-container-highest": "#e5e2de",
        "on-surface": "#1c1c1a",
        "on-background": "#1c1c1a",
        "primary": "#072078",
        "primary-container": "#26398e",
        "on-primary": "#ffffff",
        "on-primary-container": "#98a8ff",
        "primary-fixed": "#dee1ff",
        "primary-fixed-dim": "#b9c3ff",
        "inverse-primary": "#b9c3ff",
        "secondary": "#a33a42",
        "secondary-container": "#fe7f85",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#ffdad9",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "tertiary": "#3a2800",
        "tertiary-container": "#563d00",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#ffdea3",
        "tertiary-fixed-dim": "#fbbc27",
      },
      fontFamily: {
        headline: ["Montserrat", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};
export default config;
